[package]
name = "rsmq"
description = "A Rust implementation of [RSMQ](https://smrchy.github.io/rsmq/about/) (Redis Simple Message Queue)."
license = "MIT"
repository = "https://github.com/dvdplm/rsmq-rust"
version = "0.0.1"
authors = ["David Palm <dvdplm@gmail.com>"]

[dependencies]
redis = "0.8"
num-bigint = "0.1.41"
rand = "*"
#  TOOD r2d2